### ISSUE TITLE
Wrong width/height if image inside a transform with scale

### ISSUE THREAD

**Issue by Nils-1st-retail** [JafarAkhondali/lightzoom#2]
Hi I ran into a problem where if I used the zoom plugin on a image inside a transform that scales the image the zoom still uses the original image size. 
This causes a offset between the displayed image and the placement of the zoom.

This can be fixed by changing 
 ```
       var w  = obj.offsetWidth;
       var h  = obj.offsetHeight;
```
with the width / height from the bounding client.

```
       var bounding = obj.getBoundingClientRect();
       var w = bounding.width;
       var h = bounding.height;
```

**Comment by JafarAkhondali** [comment]
Hi @Nils-1st-retail ,
Thanks for reporting the bug, Why dont you submit a PR? :+1:

**Comment by JafarAkhondali** [comment]
@Nils-1st-retail I'll close the issue since you fixed the problem. Thanks
